---
title: "scRNA analysis"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: true 
    toc_depth: 1
    toc_float:
      collapsed: true
      smooth_scroll: true
    number_sections: false  
    theme: united  
    highlight: tango 
---

# Imports, paths and global variables

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

library(stringr)
library(dplyr)
library(Seurat)
library(patchwork)
library(ggplot2)
library(openxlsx)
library(harmony)
library(SingleR)
library(MuDataSeurat)

# paths
proj_path <- "/ix/djishnu/Akanksha/datasets/senescence_fibroblasts"
dataset_path <- file.path(proj_path, "all_treatments_NIA.Rds")

# mtPattern: a regex pattern to match against features to look for mitochondrial DNA; may need to adjust for
# sample species---"^MT-" works for human samples and "^mt-" for mice
mtPattern <- "^MT-"
doCite <- FALSE
```
# Inspect pre-processed Rds object
```{r load_object}
seurat_obj <- readRDS(dataset_path)
# print metadata
print(head(seurat_obj@meta.data))
```
# Convert Rds to Anndata for Tamoxifen treated cell senescence
``` {r MuDataSeurat}
# MuDataSeurat::WriteH5AD(seurat_obj, file.path(proj_path, "tam.h5ad"), assay = "RNA")
```
